# Generated by Django 5.1.1 on 2024-10-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo_url',
            field=models.URLField(null=True),
        ),
    ]
